### ISSUE TITLE
How can i add previous button in Quiz

### ISSUE THREAD

**Issue by jeevatrippy** [SafdarJamal/quiz-app#18]

**Comment by SafdarJamal** [comment]
Hello there, can you elaborate a little more on what're you trying to say?

**Comment by jeevatrippy** [comment]
I want to add previous button when we click that button need to view previously answered question 

And is there any  possibility to add bookmark for the questions

**Comment by SafdarJamal** [comment]
It seems like you want to implement a feature and don't know how to do it. If that's so, then everybody has a way of thinking and working with code. I suggest you learn [React](https://github.com/facebook/react) first before diving into the source code and then try implementing the feature by yourself. And as far the bookmarking is concerned, you can implement that by using [React Router](https://github.com/ReactTraining/react-router).
